/*
 * generated by Xtext
 */
package org.example.smalljava.ui.contentassist

import org.example.smalljava.ui.contentassist.AbstractSmallJavaProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class SmallJavaProposalProvider extends AbstractSmallJavaProposalProvider {
}
