/**
 * generated by Xtext
 */
package org.example.smalljava.validation;

import org.example.smalljava.validation.AbstractSmallJavaValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class SmallJavaValidator extends AbstractSmallJavaValidator {
}
