/**
 * generated by Xtext
 */
package org.example.expressions.ui.contentassist;

import org.example.expressions.ui.contentassist.AbstractExpressionsProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class ExpressionsProposalProvider extends AbstractExpressionsProposalProvider {
}
