/*
 * generated by Xtext
 */
package org.examples.entities.validation

import org.examples.entities.entities.Entity
import org.eclipse.xtext.validation.Check
import org.examples.entities.entities.EntitiesPackage
import static extension java.lang.Character.*
import org.examples.entities.entities.Attribute

//import org.eclipse.xtext.validation.Check

/**
 * Custom validation rules. 
 *
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
class EntitiesValidator extends AbstractEntitiesValidator {

public static val HIERARCHY_CYCLE = 
"org.example.entities.HierarchyCycle";

public static val INVALID_ENTITY_NAME =
"org.example.entites.InvalidEntityNale";

public static val INVALID_ATTRIBUTE_NAME = 
"org.example.entites.InvalidAttributeName"




@Check
def checkEntityNameStartWithCapital(Entity entity){
	if (entity.name.charAt(0).lowerCase)
		warning("Entity name should start with a capital",
			EntitiesPackage::eINSTANCE.entity_Name)
		
}




@Check
def checkNoCycleInEntityHierarchy(Entity entity)
{
	if (entity.superType == null)
		return; // nothing to check
	
	val visitedEntities = <Entity>newHashSet()
	visitedEntities.add(entity)
	
	var current = entity.superType
	while (current != null) {
		if (visitedEntities.contains(current)) {
		
		error("cycle in hierarchy of entity '" + current.name + "'", 
			EntitiesPackage$Literals::ENTITY__SUPER_TYPE, 
			HIERARCHY_CYCLE,
			current.superType.name)
			
			
			
		return
		}
		visitedEntities.add(current)
		current = current.superType
	}
	
}

//  public static val INVALID_NAME = 'invalidName'
//
//	@Check
//	def checkGreetingStartsWithCapital(Greeting greeting) {
//		if (!Character.isUpperCase(greeting.name.charAt(0))) {
//			warning('Name should start with a capital', 
//					MyDslPackage.Literals.GREETING__NAME,
//					INVALID_NAME)
//		}
//	}
}
