/**
 * generated by Xtext
 */
package org.example.expressions.validation;

import org.example.expressions.validation.AbstractExpressionsValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class ExpressionsValidator extends AbstractExpressionsValidator {
}
