/*
 * generated by Xtext
 */
package org.examples.entities.ui.contentassist

import org.examples.entities.ui.contentassist.AbstractEntitiesProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class EntitiesProposalProvider extends AbstractEntitiesProposalProvider {
}
