/**
 * generated by Xtext
 */
package org.examples.entities.ui.quickfix;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.ui.editor.model.IXtextDocument;
import org.eclipse.xtext.ui.editor.model.edit.IModification;
import org.eclipse.xtext.ui.editor.model.edit.IModificationContext;
import org.eclipse.xtext.ui.editor.model.edit.ISemanticModification;
import org.eclipse.xtext.ui.editor.quickfix.DefaultQuickfixProvider;
import org.eclipse.xtext.ui.editor.quickfix.Fix;
import org.eclipse.xtext.ui.editor.quickfix.IssueResolutionAcceptor;
import org.eclipse.xtext.validation.Issue;
import org.eclipse.xtext.xbase.lib.StringExtensions;
import org.examples.entities.entities.Entity;
import org.examples.entities.validation.EntitiesValidator;

/**
 * Custom quickfixes.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#quickfixes
 */
@SuppressWarnings("all")
public class EntitiesQuickfixProvider extends DefaultQuickfixProvider {
  @Fix(EntitiesValidator.INVALID_ENTITY_NAME)
  public void capitalizeEntityNameFirstLetter(final Issue issue, final IssueResolutionAcceptor acceptor) {
    String[] _data = issue.getData();
    String _get = _data[0];
    String _plus = ("Capitalize first letter of \'" + _get);
    String _plus_1 = (_plus + "\'");
    final IModification _function = new IModification() {
        public void apply(final IModificationContext context) throws Exception {
          final IXtextDocument xtextDocument = context.getXtextDocument();
          Integer _offset = issue.getOffset();
          final String firstLetter = xtextDocument.get((_offset).intValue(), 1);
          Integer _offset_1 = issue.getOffset();
          String _firstUpper = StringExtensions.toFirstUpper(firstLetter);
          xtextDocument.replace((_offset_1).intValue(), 1, _firstUpper);
        }
      };
    acceptor.accept(issue, "Capitalize first letter", _plus_1, 
      "Entity.gif", _function);
  }
  
  @Fix(EntitiesValidator.HIERARCHY_CYCLE)
  public void removeSuperType(final Issue issue, final IssueResolutionAcceptor acceptor) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("Remove supertype \'");
    String[] _data = issue.getData();
    String _get = _data[0];
    _builder.append(_get, "");
    _builder.append("\' ");
    final ISemanticModification _function = new ISemanticModification() {
        public void apply(final EObject element, final IModificationContext context) throws Exception {
          ((Entity) element).setSuperType(null);
        }
      };
    acceptor.accept(issue, 
      "Remove supertype", _builder.toString(), 
      "delete_obj.gif", _function);
  }
}
