/*
 * generated by Xtext
 */
package org.example.smalljava;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SmallJavaRuntimeModule extends org.example.smalljava.AbstractSmallJavaRuntimeModule {

}
