/*
 * generated by Xtext
 */
package org.examples.entities.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractEntitiesValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(org.examples.entities.entities.EntitiesPackage.eINSTANCE);
		return result;
	}
}
