/*
 * generated by Xtext
 */
package org.examples.entities;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class EntitiesRuntimeModule extends org.examples.entities.AbstractEntitiesRuntimeModule {

}
